### ISSUE TITLE
Names

### ISSUE THREAD

**Issue by rovertdude** [TotalFreedom/BukkitTelnet#10]
I suggest stuff like _ to be used in telnet usernames if possible.

**Comment by JeromSar** [comment]
@rovertdude Aren't telnet names automatically resolved to their MC usernames? Is there anything in place to actually block underscores to be used?

**Comment by rovertdude** [comment]
@JeromSar 
They aren't always - a friend of mine has a IGN of _c0ded and when he goes on telnet (he doesn't have it set to auto-connect currently) and it shows up with "c0ded" instead.

**Comment by JeromSar** [comment]
@rovertdude I don't see this as an issue, sorry.
