### ISSUE TITLE
Rcon connection name length limit

### ISSUE THREAD

**Issue by supergameplayer** [TotalFreedom/BukkitTelnet#6]
We also need to limit the length of telnet names. If someone connects with a very long name, it will reject the connection and not log it. Insanely long names for telnet can still be a problem.

**Comment by gomalley411** [comment]
Vouch. Also, speaking of names, we should have a policy on the server to /tban every user who has a curse word in his/her IGN, so people like "JustinBieberIsSh*t" would get tempbanned for an inappropriate username.

**Comment by Stampy100** [comment]
Vouch?

**Comment by supergameplayer** [comment]
@gomalley411 We don't need an anti-cuss system. Just a length limit.

**Comment by gomalley411** [comment]
I meant that I support the idea...

**Comment by ThePheonixBlader** [comment]
Vouch

**Comment by Foorah** [comment]
I vouch. c:

**Comment by JeromSar** [comment]
Irrelevant to this project. This is BukkitTelnet. :)
